name = "assignment6"
uuid = "9b3d9e3f-5d7c-5f4b-af6d-8e9f0b2c3d4e"
version = "0.1.0"
authors = ["John T. Foster <johntfosterjr@gmail.com>"]

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Test = "1.11.0"
